repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: flake8
    -   id: check-builtin-literals
    -   id: no-commit-to-branch
        args: ['--branch', 'master', '--branch', 'dev']
